# Vehicle initial positions configuration
initial_positions:
  - {x: 0.0, y: 1.0}
  - {x: 0.0, y: -1.0}
  - {x: 1.0, y: 0.0}
  - {x: -1.0, y: 0.0}

# Default PX4 configuration
px4_config:
  autostart: 4001
  model: gz_x500_mod
  world: warehouse
  px4_binary_path: ~/shared_volume/PX4-Autopilot/build/px4_sitl_default/bin/px4

# Agent configuration
agent_config:
  port: 8888
  protocol: udp4