# Node launch configuration
# Set to [enable, log_level]
# Enable: true launches the node, false does not
# Log levels: debug, info, warn, error, fatal

darp: [true, 'info']
coordinator: [true, 'info']
px4_transform: [true, 'info']