/**:
  ros__parameters:
    agents:
      ids: ["px4_1", "px4_2", "px4_3"]
      initial_positions_x: [-2.0, 0.0, 2.0]
      initial_positions_y: [0.0, 0.0, 0.0]
    tasks:
      # Área de la tarea en metros: rectángulo [min, max)
      min_x: -11
      max_x: 11
      min_y: -11
      max_y: 11
      # Posiciones de los obstáculos en metros
      obstacles_positions_x: [4.0, 4.0, 4.0, 4.0, -8.0, -8.0, -8.0, -8.0, -4.0, -2.0, 0.0, 2.0, 4.0]
      obstacles_positions_y: [2.0, 4.0, 6.0, 8.0, -4.0, -2.0, 0.0, 2.0, -4.0, -4.0, -4.0, -4.0, -4.0]
    simulation:
      enabled: true
      events_types: ["agent_failure"]
      events_times: [15.0]  # Seconds after mission start
      events_agents: ["px4_2"]