/**:
  ros__parameters:
    agents:
      ids: ["px4_1", "px4_2"]
      initial_positions_x: [0.0, -5.0]
      initial_positions_y: [0.0, -5.0]
    tasks:
      min_x: -5
      max_x: 5
      min_y: -5
      max_y: 5
      obstacles_positions_x: [1.0, 2.0, -1.0]
      obstacles_positions_y: [1.0, 2.0, -1.0]
    