/**/planning_node:
  ros__parameters:
    example_parameter: "Hello, world!"

/**/darp_node:
  ros__parameters:
    cell_size: 2.0

/**/control_node:
  ros__parameters:
    target_altitude: 5.0
    acceptance_radius: 0.5

/**/px4_transform_node:
  ros__parameters:
    example_parameter: "Hello, world!"

/**/visualization_node:
  ros__parameters:
    markers:
      line_width: 0.075
      point_scale: 0.20
      alpha: 0.85