/**/planning_node:
  ros__parameters:
    cell_size: 2.0
    visited:
      update_period: 0.5

/**/darp_node:
  ros__parameters:
    cell_size: 2.0

/**/control_node:
  ros__parameters:
    target_altitude: 5.0
    acceptance_radius: 0.5

/**/visualization_node:
  ros__parameters:
    # Parámetros de visualización de agentes
    drones:
      position_scale: 0.35
      setpoint_scale: 0.25
      arrow_width: 0.08
      label_scale: 0.4
      z_offset: 0.05
    # Parámetros de visualización de trayectorias
    trajectories:
      line_width: 0.075
      point_scale: 0.20
      alpha: 0.5
    # Parámetros de visualización de zonas
    zones:
      cell_size: 2.0
      fill_alpha: 0.075
      outline_width: 0.01