coordinator_node:
  ros__parameters:
    target_altitude: 5.0
    acceptance_radius: 0.5

darp_node:
  ros__parameters:
    example_parameter: "Hello, world!"

px4_transform_node:
  ros__parameters:
    example_parameter: "Hello, world!"